import { Link, useRouterState } from "@tanstack/react-router";
import { Bell, BriefcaseBusiness, ChartNoAxesColumnIncreasing, Clock3, Compass, GraduationCap, LayoutDashboard, LogOut, MapPin, Menu, Mic2, Settings, UserRound, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Brand } from "./brand";
import { cn } from "../lib/utils";
const nav = [
 ["/dashboard","Dashboard",LayoutDashboard], ["/profile","My Profile",UserRound], ["/jobs","Job Matches",BriefcaseBusiness], ["/skill-gaps","Skill Gaps",ChartNoAxesColumnIncreasing], ["/training","Training & Courses",GraduationCap], ["/time-to-ready","Time-to-Ready",Clock3], ["/roadmap","Career Roadmap",Compass], ["/voice-assistant","Voice Assistant",Mic2], ["/settings","Settings",Settings],
] as const;
export function AppShell({ children }: { children: ReactNode }) {
 const [open,setOpen]=useState(false); const path=useRouterState({select:s=>s.location.pathname});
 return <div className="min-h-screen bg-background"><aside className={cn("fixed inset-y-0 left-0 z-40 w-64 bg-sidebar p-5 text-sidebar-foreground transition-transform lg:translate-x-0",open?"translate-x-0":"-translate-x-full")}><div className="flex items-center justify-between"><Brand/><button aria-label="Close menu" className="lg:hidden" onClick={()=>setOpen(false)}><X/></button></div><nav className="mt-9 space-y-1">{nav.map(([to,label,Icon])=><Link key={to} to={to} onClick={()=>setOpen(false)} className={cn("flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold text-sidebar-foreground/70 transition hover:bg-sidebar-foreground/10 hover:text-sidebar-foreground",path===to&&"bg-primary text-primary-foreground")}><Icon size={18}/>{label}</Link>)}</nav><Link to="/" className="absolute bottom-5 left-5 right-5 flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold text-sidebar-foreground/70 hover:bg-sidebar-foreground/10"><LogOut size={18}/>Logout</Link></aside>{open&&<button aria-label="Close menu overlay" className="fixed inset-0 z-30 bg-foreground/30 lg:hidden" onClick={()=>setOpen(false)}/>}<div className="lg:pl-64"><header className="sticky top-0 z-20 flex h-17 items-center justify-between border-b bg-card/95 px-4 backdrop-blur md:px-7"><button aria-label="Open menu" onClick={()=>setOpen(true)} className="lg:hidden"><Menu/></button><div className="hidden items-center gap-2 text-sm font-semibold text-muted-foreground sm:flex"><MapPin size={17} className="text-primary"/>Hyderabad, Telangana</div><div className="ml-auto flex items-center gap-4"><button aria-label="Notifications" className="relative text-muted-foreground"><Bell size={20}/><span className="absolute -right-0.5 -top-0.5 size-2 rounded-full bg-danger"/></button><div className="flex items-center gap-2"><span className="grid size-9 place-items-center rounded-full bg-secondary text-sm font-extrabold text-primary">AR</span><div className="hidden text-xs sm:block"><strong className="block">Aarav Reddy</strong><span className="text-muted-foreground">Aspiring Developer</span></div></div></div></header><main className="mx-auto max-w-7xl p-4 md:p-7">{children}</main></div></div>
}
